language: python
python:
    - "2.7"
    - "3.4"
sudo: required
# command to install dependencies
install:
    - "pip install -r testing-requirements.txt"
# command to run tests
script: lettuce Lettuce_Tests