language: python

sudo: false

cache: pip

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  allow_failures:
  - python: 3.6
    env: TEST_TARGET=default

install:
    - pip install -r requirements.txt -r requirements-dev.txt

script:
  - lettuce --tag=-not_working Lettuce_Tests
